services:
  chromadb:
    image: chromadb/chroma
    ports:
      - "8000:8000"
    volumes:
      - chromadb_data:/chroma/chroma

  chromadb-admin:
    image: fengzhichao/chromadb-admin
    platform: linux/arm64
    ports:
      - "3001:3001"

volumes:
  chromadb_data:
    driver: local
